### ISSUE TITLE
hard time getting ytel to work with new invidious api url

### ISSUE THREAD

**Issue by Luis-Henriquez-1** [gRastello/ytel#15]
_https://invidio.us_ is down. I tried switching to another one of the mirrors e.g. `(setq ytel-invidious-api-url "https://invidious.snopyta.org/")`  but to no avail. I either get a "wrong-type argument (array timed out)" or an empty search buffer or "end of file while parsing json". Do you experience the same thing or am I the only one?

**Comment by pablobc-mx** [comment]
Take out the slash at the end. It should be `(setq ytel-invidious-api-url "https://invidious.snopyta.org")`.

**Comment by Luis-Henriquez-1** [comment]
Ah, I'm a noob. That worked out, thank you! This is an excellent package.
